---
# Products we currently support 
:products:
    # Format: "product reference": "directory name in framework"
    ks: 'ks'
    oae: 'oae'
# Directory listing for test data in use in the tests
:directory:
    # Product for directory data
    ks:
        department_coc:
            name: "Fisheries Department COC"
            member:
                username: "fishdptcoc1"
                password: "fishdptcoc1"
            chair:
                username: "fishdptchair1"
                password: "fishdptchair1"
        department:
            name: "Fisheries Department"
            member:
                username: "fishon1"
                password: "fishon1"
        division:
            name: "Oceanography Division"
        division_coc:
            name: "Oceanography Division COC"
            member:
                username: "fishdvcoc1"
                password: "fishdvcoc1"
            chair:
                username: "fishdvchair1"
                password: "fishdvchair1"
        college:
            name: "The College of Ocean and Fishery Sciences"
        college_coc:
            name: "The College of Ocean and Fishery Sciences"
            member:
                username: "fishcollegec1"
                password: "fishcollegec1"
            chair:
                username: "fishcollegechair9"
                password: "fishcollegechair9"
        senate:
            name: "Senate Subcommittee on Curricula"
            member:
                username: "senate1"
                password: "senate1"
            chair:
                username: "senatechair"
                password: "senatechair"
        atp:
            name: "Class of 2012 Year 1"
        lo:
            name: "Performance LO"
        users:
            collaborator:
                username: "fran"
# Agent List
:agents:
    # IE 7.0 - XP
    - "Mozilla/5.0 (Windows; MSIE 7.0; Windows NT 6.0; en-US)"
    # IE 6.0 - Vista
    - "Mozilla/4.0 (Windows; MSIE 6.0; Windows NT 6.0)"
    # FireFox 3.5.7 - Vista
    - "Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US)"
    # FireFox 3.5.6 - OSX 10.6 (Snow Leopard)
    - "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.1.6) Gecko/20091201 Firefox/3.5.6"
    