---
department_coc:
    name: "Fisheries Department COC"
    member:
        username: "fishdptcoc1"
        password: "fishdptcoc1"
    chair:
        username: "fishdptchair1"
        password: "fishdptchair1"
department:
    name: "Fisheries Department"
    member:
        username: "fishon1"
        password: "fishon1"
division:
    name: "Oceanography Division"
division_coc:
    name: "Oceanography Division COC"
    member:
        username: "fishdvcoc1"
        password: "fishdvcoc1"
    chair:
        username: "fishdvchair1"
        password: "fishdvchair1"
college:
    name: "The College of Ocean and Fishery Sciences"
college_coc:
    name: "The College of Ocean and Fishery Sciences"
    member:
        username: "fishcollegec1"
        password: "fishcollegec1"
    chair:
        username: "fishcollegechair9"
        password: "fishcollegechair9"
senate:
    name: "Senate Subcommittee on Curricula"
    member:
        username: "senate1"
        password: "senate1"
    chair:
        username: "senatechair"
        password: "senatechair"
atp:
    name: "Class of 2012 Year 1"
lo:
    name: "Performance LO"
users:
    collaborator:
        username: "fran"